CREATE TABLE Subject(
SubjectID VARCHAR(100) NOT NULL,
Age DECIMAL (13,10),
Sex CHAR(1),
BMI DECIMAL(4,2),
Insulin_Class CHAR(2),
PRIMARY KEY (SubjectID)
);


CREATE TABLE Sample (
SampleID VARCHAR(100) NOT NULL,
SubjectID VARCHAR(100) NOT NULL,
VisitID VARCHAR(100) NOT NULL,
FOREIGN KEY (SubjectID) REFERENCES Subject(SubjectID)
);

CREATE TABLE Transcriptome_Abundance (
SampleID VARCHAR(100) NOT NULL,
SubjectID VARCHAR(100) NOT NULL,
VisitID VARCHAR(100) NOT NULL,
A1BG REAL,
FOREIGN KEY (SubjectID) REFERENCES Subject(SubjectID)
);

CREATE TABLE Proteome_Abundance (
SampleID VARCHAR(100) NOT NULL,
SubjectID VARCHAR(100) NOT NULL,
VisitID VARCHAR(100) NOT NULL,
FOREIGN KEY (SubjectID) REFERENCES Subject(SubjectID)
);

CREATE TABLE Metabolome_Abundance (
SampleID VARCHAR(100) NOT NULL,
SubjectID VARCHAR(100) NOT NULL,
VisitID VARCHAR(100) NOT NULL,
FOREIGN KEY (SubjectID) REFERENCES Subject(SubjectID)
);

CREATE TABLE Metabolome_Annotation (
PeakID VARCHAR(100),
KEGGID VARCHAR(100),
Pathway VARCHAR(300),
Metabolite_Name VARCHAR(200)
);
